name: s_factory
description: A new Flutter project.
#   flutter pub run build_runner build --delete-conflicting-outputs


publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  # flutter_easyloading: ^3.0.5
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  json_serializable: ^6.7.1
  retrofit: ^4.0.3
  flutter_svg: ^2.0.9
  connectivity_plus: ^3.0.2
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0
  mobile_scanner: ^3.5.2
  equatable: ^2.0.5
  pinput: ^3.0.1
  graphql_flutter: ^5.2.0-beta.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
